var data = [
    {
      "Nome": "Anderson Freire",
      "Empresa": "Empreendedor",
      "EXPERTISE": "Empreendedorismo e Negócios.",
      "Picture": "https://api.typeform.com/responses/files/627ed1e7291721a223f38b51257263141a38af7735660d3725687cfa269bde6c/05d02003_4008_4af6_8081_7f16c4a5073b.jpg",
      "mini_curriculo": "Um dos organizadores da Campus Party BSB. Ajudamos a tirar sua ideia do papel",
      "BackGround": "Empreendedorismo e Negócios. Um dos organizadores da Campus Party BSB. Ajudamos a tirar sua ideia do papel",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Ricardo Freire",
      "Empresa": "Força Area Brasileira",
      "EXPERTISE": "Mestre Engenhharia Aeroespacial em Roma",
      "Picture": "https://api.typeform.com/responses/files/742bdc9a08b0f7193f72d0c1a9dee4460e8afb69bc36804c6538f148f1444d30/IMG_20180720_WA0035__1_.jpg",
      "mini_curriculo": "Gestor técnico comando de Operações Aeroespaciais e projeto Sistema Espacial CARPONIS do Ministério da Defesa. Criador canal Um Pequeno Passo com mais 212 mil visualizações.",
      "BackGround": "MSc Engenharia Aeroespacial, Universidade de Roma \"La Sapienza\". Gestor técnico comando de Operações Aeroespaciais e projeto Sistema Espacial CARPONIS do Ministério da Defesa. Criador canal Um Pequeno Passo com mais 212 mil visualizações.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Paulo  Cotta",
      "Empresa": "Startup",
      "EXPERTISE": "Machine Learning, Deep Learning, Python e Java,",
      "Picture": "https://api.typeform.com/responses/files/dfefefa0b4d412b6f82f38ce979be93035990e50997b8df760fa9f3a405818b0/Paulo.jpeg",
      "mini_curriculo": "Mestrado na Unb. Atuo com Machine Learning, Deep Learning, Python, Java, conhecimentos em Web.",
      "BackGround": "Mestrado na Unb. Atuo com Machine Learning, Deep Learning, Python, Java, conhecimentos em Web.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Alessandra Peguim Rosa",
      "Empresa": "Instituto Eldorado",
      "EXPERTISE": "Comunicação e Marketing em Interação Humano Computador - Unicamp.",
      "Picture": "https://api.typeform.com/responses/files/cefab1b6e4ad5b108019a7b0a26cda7ae0272966c370bdc1d75832fa184df0a5/IMG_20191214_210203_646.jpg",
      "mini_curriculo": "Especialista em Transformação Digital com foco em 3 pilares - tecnologia / Foco no Usuário e Negócios",
      "BackGround": "Comunicação e Marketing em Interação Humano Computador - Unicamp. Especialista em Transformação Digital com foco em 3 pilares - tecnologia / Foco no Usuário e Negócios",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Leonardo Julio Chagas Souza",
      "Empresa": "Agência Espacial Brasileira",
      "EXPERTISE": "Engenharia Aeroespacial - UnB.",
      "Picture": "https://api.typeform.com/responses/files/b2899b67c73559405e3ca4c9c64c07cc3c843f0821e7f1d2b284e99945fe39f0/57453584_10219541572074913_5548944841301295104_o.jpg",
      "mini_curriculo": "Gestor de parcerias do Space Generation Advisory Council  América Latina.  Formação em  inovação e empreendedorismo pela Georgetown University.",
      "BackGround": "Engenharia Aeroespacial - UnB. Gestor de parcerias do Space Generation Advisory Council América Latina. Formação em inovação e empreendedorismo pela Georgetown University.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Thiago Miotelo",
      "Empresa": "Empreendedor",
      "EXPERTISE": "Negócios e Empreendedorismo",
      "Picture": "https://i.stack.imgur.com/l60Hf.png",
      "mini_curriculo": "Especialista em começar do zero sem dinheiro. Ajudo você a tirar sua startup do papel e construir um negócio inovador.",
      "BackGround": "Empreendedor desde sempre. Especialista em começar do zero sem dinheiro. Ajudo você a tirar sua startup do papel e construir um negócio inovador.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Thálisson Lopes",
      "Empresa": "UDF",
      "EXPERTISE": "Internet das Coisas,m Inteligência Artifificial e  inovação.",
      "Picture": "https://api.typeform.com/responses/files/2b464fa5685c5960d62ab88daed2820081e1e1083b18f12cf1a28d22a7ed6089/Foto_Thalisson.png",
      "mini_curriculo": "Atuamos com Internet das Coisas (IoT), BlockChain e Big Data nas áreas de Saúde (HealthTech), Tecnologias Agrícolas (AgroTech) e Direito (LegalTech).",
      "BackGround": "Empreendedor, Startupeiro, curioso por Tecnologia. Atuamos com Internet das Coisas (IoT), BlockChain e Big Data nas áreas de Saúde (HealthTech), Tecnologias Agrícolas (AgroTech) e Direito (LegalTech).",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Johann Bischof",
      "Empresa": "Sebrae DF",
      "EXPERTISE": "Especialista em planejamento e projetos.",
      "Picture": "https://api.typeform.com/responses/files/d0da897160d4dc5b04c532a88388b851ce8fc18b152ea4cac8119f2dddca7131/3X4.png",
      "mini_curriculo": "Gestor de Startups do Sebrae DF desde 2017.",
      "BackGround": "Especialista em planejamento e projetos. Gestor de Startups do Sebrae DF desde 2017.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Rodrigo Fay Vergara",
      "Empresa": "Startup",
      "EXPERTISE": "Tecnologia  - Inteligencia Artificial",
      "Picture": "rodrigo_vergara.jpeg",
      "mini_curriculo": "Eng eletrônico  e mestre eng biomédica - UnB.",
      "BackGround": "Eng eletrônico e mestre eng biomédica - UnB. Especialista em Inteligência Artifificial e amante da inovação.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Orlan Almeida",
      "Empresa": "Startup GIANT",
      "EXPERTISE": "IOT - Tecnologia -  Pitch - Negócios",
      "Picture": "https://api.typeform.com/responses/files/fc9ac4df6df1b61794cb681032b4e2d08f0b0239e089570c45dc1ff6820dad86/74C4F751_65C5_47BD_A53D_B9F5F8CB1B1C.jpeg",
      "mini_curriculo": "IOT - Tecnologia -  Pitch - Negócios",
      "BackGround": "Head de Inovacao, GIANT. Fundador de Startups e mentor de aceleradoras do Vale do Silicio. Engenheiro com atuação em IOT. \nEspecialista em Tecnologias disruptivas \nMentor do Founder, programa de pré-aceleração \nProfessor no MBA de negócios disruptivos",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Carolina Garcia",
      "Empresa": "Startup Pactu Studio",
      "EXPERTISE": "Design - Comunicação - Projetos",
      "Picture": "carolin_garcia.png",
      "mini_curriculo": "Larga experiência com processos criativos, design, comunicação e gestão de projetos.",
      "BackGround": "Ex Diretora de Whatever na Perestroika, maior escola de atividades criativas da América Latina. Empreendedora de um estúdio que faz coisas visuais, chamada \"Pacu Studio\".Larga experiência com processos criativos, design, comunicação e gestão de projetos.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Rodrigo Alves",
      "Empresa": "Empreendedor",
      "EXPERTISE": "Especialista em produtos e Led Growth - UX - UI",
      "Picture": "https://api.typeform.com/responses/files/83b995d26ea2793af1c647389e872f22059c47af0f8a3d836d20d4a639437857/WhatsApp_Image_2020_09_08_at_07.57.53.jpeg",
      "mini_curriculo": "Especialista em produtos e Led Growth - UX - UI",
      "BackGround": "8 anos de experiência com produtos digitais. Fundador de Startups e Empreendedor desde sempre.\n3 anos de experiência com empreendedorismo digital\nUm dos 4 graduados na 1a turma do Founder Institute em Brasília\nGerente de Produto na Axur - Segurança Cibernética\nEspecialista em Product-Led Growth",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Fabrício Olivieri",
      "Empresa": "Tecnolta",
      "EXPERTISE": "Designer. Gráfico , Negócios e  Empreendedorismo",
      "Picture": "https://api.typeform.com/responses/files/932be4af7aaecbb69047b6c4958aee2d8b21610e0cbe1f03877594178422eda4/1FD7908C_145B_4751_B985_587EE067A788.jpeg",
      "mini_curriculo": "Designer gráfico, empresário no ramo de TI e humanista. Ainda tentando entender qual meu quinhão nos próximos passos da humanidade.",
      "BackGround": "Designer gráfico, empresário no ramo de TI e humanista. Ainda tentando entender qual meu quinhão nos próximos passos da humanidade.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Ramires Barreto",
      "Empresa": "Empreendedor",
      "EXPERTISE": "UX - UI - DEV- Negócios  - Tecnologia",
      "Picture": "https://api.typeform.com/responses/files/abc011131901ca4c2fb3e86fdbc6d8c95af08078b22c80bae53e0761905868da/ramires.jpeg",
      "mini_curriculo": "1 - Estrategista de mídia\n2 - Dono de agência publicidade de pequeno porte\n3 - Dono de produtora digital\n4 - Clientes nacionais e internacionais\n5 - Desenvolvimento de Produtos escaláveis",
      "BackGround": "1 - Estrategista de mídia\n2 - Dono de agência publicidade de pequeno porte\n3 - Dono de produtora digital\n4 - Clientes nacionais e internacionais\n5 - Desenvolvimento de Produtos escaláveis",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Luis Felipe  Nohra",
      "Empresa": "Força Area Brasileira",
      "EXPERTISE": "Especialista em Satélites e Engenharia Aeroespacial",
      "Picture": "https://api.typeform.com/responses/files/7e46f69ee899fdb181a5d7451b5b4a9d38feabdf25931295e7318bdd683c0d4c/EDEAE3E0_C837_4239_902D_A3972F4A4178.jpeg",
      "mini_curriculo": "Mestre em Ciências pelo ITA, Especialista em Satélites, Piloto da Força Aérea e YouTuber.",
      "BackGround": "Mestre em Ciências pelo ITA, Especialista em Satélites, Piloto da Força Aérea e YouTuber.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Zeca lucas",
      "Empresa": "Empreendedor Tecnologia",
      "EXPERTISE": "Desenvolvimento. - Ciencia de dados - Tecnologia Computacional",
      "Picture": "https://api.typeform.com/responses/files/862d2421ec03063b89d817e42bd2221372bc7e107ccf0120020fb475e102fb42/20200926_222007.jpg",
      "mini_curriculo": "Buscador, empreendedor, pai e amigo. \nJá fundei mais de 6 empresas na área de tecnologia, desenvolvo em mais de 10 linguagens e coordenei a equipe de tecnologia do MEC, sendo responsável por criar o SISU, FIES E PROUNI",
      "BackGround": "Buscador, empreendedor, pai e amigo. \nJá fundei mais de 6 empresas na área de tecnologia, desenvolvo em mais de 10 linguagens e coordenei a equipe de tecnologia do MEC, sendo responsável por criar o SISU, FIES E PROUNI",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Eliane Raye Vallim",
      "Empresa": "Startup GIANT",
      "EXPERTISE": "Empreendedorismo - Pitch  - Negócios",
      "Picture": "https://api.typeform.com/responses/files/ae57eda9ed156ef5493c9b9a7d817588ad5e587864603fa5d84ac43a8985cf5b/Eliane_Raye.jpeg",
      "mini_curriculo": "",
      "BackGround": "Empreendedora. Ex ondotologa. Ex Roqueira. Publiquei 3 livros de ficção. Fundei Startups e agora estou na Nasa com vocês.\nIlustrei 9 livros infantis\nGestora do Sebraelab e Coordenadora dos Agentes Locais de Inovação\nHead de Criatividade da GIANT",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Andre Wogel",
      "Empresa": "Startup",
      "EXPERTISE": "Tecnologias Experimentais para educação - Eletrônica",
      "Picture": "https://api.typeform.com/responses/files/66713274de039acdabbfc74f8a98e02218e5f9b4f93d8790ece43b99499142d8/FE5651C3_7052_43D9_8434_8ADF51AA70DA.png",
      "mini_curriculo": "Cientista empreendedor: Uso da tecnologia experimental  aplicada a educação e inclusão digital.",
      "BackGround": "Cientista empreendedor: Uso da tecnologia experimental aplicada a educação e inclusão digital.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Ana Carolina de Freitas",
      "Empresa": "Instituto Nous",
      "EXPERTISE": "Designer - Biomimética - Metodos Agéis - Startups - Pitch",
      "Picture": "https://api.typeform.com/responses/files/0f3fe6891da1c66394ab680a848a60853bde3fae40a52e88c1ad2dc0f294b8c7/_MG_6129_PS2.jpg",
      "mini_curriculo": "Mestre em ciência Biomimética pela Arizona State University. Facilitadora de inovação e Biomimeticista. Acompanho empresas para gerarem novas formas de pensar produtos, serviços, marcas com metodologias de design e inspiração na natureza.",
      "BackGround": "Mestre em ciência Biomimética pela Arizona State University. Facilitadora de inovação e Biomimeticista. Acompanho empresas para gerarem novas formas de pensar produtos, serviços, marcas com metodologias de design e inspiração na natureza.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Gabriela Vivan",
      "Empresa": "AUTO DESK",
      "EXPERTISE": "Designer Computacional  - Tecnologia - IA",
      "Picture": "https://api.typeform.com/responses/files/22eb822c7acaa266e10b4e3631cde24444d8296a3f9aefb1f5e7ae6d230b5962/Gabi.jpg",
      "mini_curriculo": "Apaixonada por design computacional e tecnologia/AI aplicada à construção civil",
      "BackGround": "Apaixonada por design computacional e tecnologia/AI aplicada à construção civil; Atualmente head de projeto na Autodesk Toronto (Canadá); Formação complementar em Harvard (EUA) e Delft (Países Baixos); Ex-Global Nominee do S.A. Challenge (2018) e mentora ano passado!; Mentora permanente/convidada pelo programa de aceleração da Aceleradora Evoa - Maringá.",
      "": "Formação complementar em Harvard (EUA) e Delft (Países Baixos)",
      "__1": "Ex-Global Nominee do S.A. Challenge (2018) e mentora ano passado!",
      "__2": "Mentora permanente/convidada pelo programa de aceleração da Aceleradora Evoa - Maringá."
    },
    {
      "Nome": "Ismael Paiva",
      "Empresa": "Copersystem",
      "EXPERTISE": "Mestre em ciência Biomimética",
      "Picture": "https://api.typeform.com/responses/files/f7d885f0b1f3d5539ccf83eddc44a6b290ff932a7fc1ab0d77f9e3f3e7a81e2f/36012B4F_0B68_4EF1_BAF2_3222899DEAC1.jpeg",
      "mini_curriculo": "Head de Produtos na Coopersystem. É apaixonado por startups, inovação e boas ideias. Pós graduação em Tecnologia da informação",
      "BackGround": "Head de Produtos na Coopersystem. É apaixonado por startups, inovação e boas ideias. Pós graduação em Tecnologia da informação",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Anderson Lobo Feitosa",
      "Empresa": "Startup",
      "EXPERTISE": "Projetos - Marketing - Inovação - Pitch",
      "Picture": "https://api.typeform.com/responses/files/988ead79a372b58899b4e6c416ae10dc1d6321243185b27918b09037a6e4216d/B56A8AD6_7F14_4BCE_8ACA_B6E4AA0F9CCE.jpeg",
      "mini_curriculo": "Projetos - Marketing - Inovação - Pitch",
      "BackGround": "'- Arquiteto de soluções\n- Estratégia de APIs\n- Foco em backend\n- Ninja em docker, git e automação\n- Usuário experiente de AWS",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Victor Luidgi",
      "Empresa": "Plano Consultoria",
      "EXPERTISE": "Projetos - Marketing - Inovação - Pitch",
      "Picture": "https://api.typeform.com/responses/files/35c2a63e3f13f3ca85bc8da6d00c92cd1e02ef486d6350388ca5364e21a193b0/FC37BD39_2BF0_47E5_866D_3D4B6B33F291.jpeg",
      "mini_curriculo": "Gestor de marketing há 15 anos com experiência em grandes marcas nacionais e internacionais. \nEmpreendedor atuante.\nMentor de startups.\nArtesão na transformação cultural e estrutural de empresas.",
      "BackGround": "Gestor de marketing há 15 anos com experiência em grandes marcas nacionais e internacionais. \nEmpreendedor atuante.\nMentor de startups.\nArtesão na transformação cultural e estrutural de empresas.",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Francisco Severiano",
      "Empresa": "Uni Anhanguera",
      "EXPERTISE": "Astrofisica",
      "Picture": "https://api.typeform.com/responses/files/465b07d28a0d2b233409f2c9c7da500d3ef61078bea5c3eea8f328e4ed6d0beb/1601139608613190750042602314049.jpg",
      "mini_curriculo": "Entusiasta  de astrofísica, busca de meios para mestrado e doutorado em engenharia de energia solar,  estrurar cadeia de carbono pelo resgate ambiental urbano,  mobilidade elétrica",
      "BackGround": "Entusiasta de astrofísica, busca de meios para mestrado e doutorado em engenharia de energia solar, estrurar cadeia de carbono pelo resgate ambiental urbano, mobilidade elétrica",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Mariana Campos",
      "Empresa": "Empreendedor",
      "EXPERTISE": "Inovação - Pitch  - Startups",
      "Picture": "https://api.typeform.com/responses/files/03a97c002e6682b403a0689a2a3b6b255d66775c3b600ce6e74104c08d449c69/download.png",
      "mini_curriculo": "Empreendedora quase ex servidora pública. Atuo, desde 2016, em diversas iniciativas voltadas ao desenvolvimento do empreendedorismo e da inovação",
      "BackGround": "Empreendedora quase ex servidora pública. Atuo, desde 2016, em diversas iniciativas voltadas ao desenvolvimento do empreendedorismo e da inovação",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Estéfano Flenik",
      "Empresa": "Empreendedor",
      "EXPERTISE": "Negócios - Inovação - Pitch",
      "Picture": "https://api.typeform.com/responses/files/2dc3db8e506b3e01d5f0dc175d9ec4c3a8517f39c65b3ced0c064711c3331bac/4191F1F7_2473_43CD_9252_4B2E24A9BE9E.jpeg",
      "mini_curriculo": "Empresário da Inovação e Investimentos",
      "BackGround": "Empresário da Inovação e Investimentos",
      "": "",
      "__1": "",
      "__2": ""
    },
    {
      "Nome": "Bárbara Lins",
      "Empresa": "Descobertas da Bárbara",
      "EXPERTISE": "Comunicação e Marketing - Inovação - Pitch",
      "Picture": "https://api.typeform.com/responses/files/e1325082eb663e387d2ea2d03f9ad524bbdccd593ae61e4dfb3916d030aa78ce/14FD3006_CA7F_414D_AC20_06C29BB5A818.jpeg",
      "mini_curriculo": "Ex Repórter da Rede Globo durante 8 anos, criadora do site Descobertas Bárbaras, mentora de comunicação e marketing, professora universitária de comunicação, coordenadora de podcasts.",
      "BackGround": "Ex Repórter da Rede Globo durante 8 anos, criadora do site Descobertas Bárbaras, mentora de comunicação e marketing, professora universitária de comunicação, coordenadora de podcasts.",
      "": "",
      "__1": "",
      "__2": ""
    }
  ];